spec:
  replicas: 
  selector:
    matchLabels:
      app: v1 

spec:
  capacity:
    storage:
  volumeMode:
  accessModes:
  persistentVolumeReclainPolicy:
  containers:


  - image: nginx
    name: nginx
    port:

    ports:
    - name:  qwq
      containerPort: 8080

    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      httpGet: 
