apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-web
spec:
  selector:
    matchLabels:
      app: ratings-web
  template:
    metadata:
      labels:
        app: ratings-web 
    spec:
      containers:
      - name: ratings-web
        image: acr7041.azurecr.io/ratings-web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
        env:
        - name: API 
          value: http://ratings-api.ratingsapp.svc.cluster.local
        resources:
          requests: # minimum resources required
            cpu: 250m
            memory: 64Mi
          limits: # maximum resources allocated
            cpu: 500m
            memory: 512Mi